# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-18 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Street_address1',
            new_name='street_address1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Street_address2',
            new_name='street_address2',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Town_or_city',
            new_name='town_or_city',
        ),
    ]
